### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by fccc0239b79** [fccc0239b79/PChecker#11]
In the validation screen, when you want to add new part, then you need it validate with motherboard, I think there is missing "socket type", when I was trying to add part and I forgot what motherboard has what socket type, I have had to do everything again. Please add this feature.

**Comment by gregl33** [comment]
Fixed, when adding a motherboard as a new part it has an input box for "Socket", also now it validates if inputs are correct and valid with the database, so now it should add new parts every time with no errors
