### ISSUE TITLE
ADMIN panel

### ISSUE THREAD

**Issue by fccc0239b79** [fccc0239b79/PChecker#12]
There is a question, should we have (in admin panel) buttons: "create account", "edit account", "view account" if yes, what should they do ? I think we do not need them. The similar problem is with "create build" , "edit build","view build". I think that we do not need "edit build " or "view Build", because in " view build" we can build, view and edit, so or we leave just one button which is doing all of these function or we should remove rest. What do you think?

**Comment by gregl33** [comment]
we can keep "edit account" to change an account from user to admin 
"create account", and , "view account" you can delete 
I agree with the second part, delete "create build" , "edit build", as those function are done in "view build"

**Comment by gregl33** [comment]
fixed and completed
