### ISSUE TITLE
Greg - Server 

### ISSUE THREAD

**Issue by TomaszSzelachowski** [fccc0239b79/PChecker#3]
Ogolne
- Make sure the server is up and running
- Make sure you can make a new account on the server

Sunday
- Transfer the code from the old program to the new one ( make sure it works using old server)
             - All the old code that worked (the connection to server is now called serverControl) 

LOOK AT THIS FIRST
- Write code (separate if needed so we can use it later) to make sure we can save, edit, delete builds (must be done THIS IS SUPER IMPORTANT (worst case scenario test on monday but should be running maybe with minor tweaks) )

**Comment by TomaszSzelachowski** [comment]
Before coding make sure you have the up to date code and synced, before doing commits

**Comment by gregl33** [comment]
Second task complete you can register a new user 
Also started to work on retrieving builds from database and creating them
